#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  get-duckdb-version:
    name: Read supported DuckDB version
    runs-on: ubuntu-latest
    outputs:
      duckdb_version: ${{ steps.version.outputs.duckdb_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/duckdb-version
          sparse-checkout-cone-mode: false
      - id: version
        run: echo "duckdb_version=$(cat .github/duckdb-version)" >> "$GITHUB_OUTPUT"

  duckdb-stable-build:
    name: Build supported release
    needs: get-duckdb-version
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: ${{ needs.get-duckdb-version.outputs.duckdb_version }}
      ci_tools_version: ${{ needs.get-duckdb-version.outputs.duckdb_version }}
      extension_name: packetquapture
      exclude_archs: 'windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads'
      opt_in_archs: 'windows_arm64'
      reduced_ci_mode: ${{ github.event_name == 'pull_request' && 'enabled' || 'disabled' }}

  code-quality-check:
    name: Code Quality Check
    needs: get-duckdb-version
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@main
    with:
      duckdb_version: ${{ needs.get-duckdb-version.outputs.duckdb_version }}
      ci_tools_version: ${{ needs.get-duckdb-version.outputs.duckdb_version }}
      extension_name: packetquapture
      format_checks: 'format;tidy'
